server:
  port: 9003

spring:
  application:
    name: report9003

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.113.80.250:3306/dachuang?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: wzq7791671..

    # `Hikari 连接池配置`
    # `最小空闲连接数量`
    hikari:
      minimum-idle: 5
      # `空闲连接存活最大时间，默认600000（10分钟）`
      idle-timeout: 600000
      # `连接池最大连接数，默认是10
      maximum-pool-size: 10
      # `此属性控制从池返回的连接的默认自动提交行为,默认值：true`
      auto-commit: true
      # `连接池名称`
      pool-name: MyHikariCP
      # `此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # `数据库连接超时时间,默认30秒，即30000`
      connection-timeout: 30000
      connection-test-query: SELECT 1

mybatis:
  #实体类的存放路径
  type-aliases-package: com.wzq.da.chuang.model.pojos
  mapper-locations: classpath:mappers/**/*.xml

  configuration:
    map-underscore-to-camel-case: true  #开启驼峰功能
