server:
  port: 8001

spring:
  application:
    name: gateway-web

  #Redis配置
  redis:
    host: 192.168.169.140
    port: 6379

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE

      routes:
        #report9003微服务
        - id: da_chuang_report
          #lb轮询，但是没有复制多个服务，还不算分布式
          uri: lb://report9003
          predicates:
            - Path=/api/report/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter #请求数限流 名字不能随便写 ，使用默认的facatory
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
        #用户微服务
        - id: da_chuang_security
          uri: lb://security9001
          predicates:
            - Path=/api/oauth/**
          filters:
            - StripPrefix=1


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true

management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true